name: 'Geneva Fit, LLC'
favicon: null
layout_spectrum: 0.22769080381840467
typography_spectrum: 0.3551643455866724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#00cde5'
    - '#fe7700'
    - '#7c7c7c'
  brandStrength: 0.9674744156654924
  lightness: 0.646573075093329
  saturation: 0.8728614451829344
  rhythmicContrast: 0.7411045324988663
purpose: []
